### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by uhlhosting** [christopher-kapic/kapic-caprover-apps#1]
Is this down?

**Comment by christopher-kapic** [comment]
It seems to be working for me. Can you give more information about the problem you're having?

**Comment by christopher-kapic** [comment]
Resolving for inactivity

**Comment by uhlhosting** [comment]
It gave me an 404 on https://oneclickapps.caprover.christopherkapic.com

**Comment by christopher-kapic** [comment]
So there isn't actually a website to see at the root path, but it still works when you add the domain to your one-click-apps third party repositories on CapRover. Let me know if you still have problems.
